disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - cyclomatic_complexity
  - identifier_name

opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_acl
  - explicit_self
  - explicit_top_level_acl
  - fatal_error_message
  - first_where
  - toggle_bool

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

line_length: 150

type_body_length:
  - 200 # warning
  - 300 # error

function_body_length:
  warning: 10
  error: 100

file_length:
  warning: 300
  error: 550

vertical_whitespace:
  max_empty_lines: 2

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 30
    error: 40
